name: terraformBuild

on:
  push:
    branches:
      - main   # Triggers the workflow when code is pushed to the main branch
  workflow_dispatch:

jobs:
  terraformCheckJobs:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform check
        run: terraform version

      - name: Terraform initialization
        run: terraform init


